version: "3.8"

services:

  accounts:
    image: va1b4av/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - va1b4av-network
    
  loans:
    image: va1b4av/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - va1b4av-network
    
  cards:
    image: va1b4av/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - va1b4av-network
    
networks:
  va1b4av-network: